function doScatter(X1, Y1, S1, C1, X2, Y2, C2)
%CREATEFIGURE(X1, Y1, S1, C1, X2, Y2, C2)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  X2:  scatter x
%  Y2:  scatter y
%  C2:  scatter c

%  Auto-generated by MATLAB on 22-Nov-2015 14:03:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontName','Lato');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-12 12]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-12 12]);
box(axes1,'on');
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,C1,'DisplayName','A');

% Create scatter
scatter(X2,Y2,S1,C2,'DisplayName','inverse of A','Marker','x');

% Create xlabel
xlabel('Determinant');

% Create ylabel
ylabel('Trace');

% Create title
title('Determinant vs Trace in A and inverse of A');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.545294945762421 0.197611294986111 0.216998188232643 0.11726384073593]);

% Create colorbar
colorbar('peer',axes1);

