function scatterAI(X1, Y1, S1, C1, C2)
%CREATEFIGURE(X1, Y1, S1, C1, C2)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  C2:  scatter c

%  Auto-generated by MATLAB on 23-Nov-2015 13:26:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontName','Arial');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-3 3]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-3 3]);
box(axes1,'on');
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,C1,'DisplayName','A','Visible','off');

% Create scatter
scatter(X1,Y1,S1,C2,'DisplayName','inverse of A','Marker','x');

% Create xlabel
xlabel('Determinant');

% Create ylabel
ylabel('Trace');

% Create title
title('Determinant vs Trace in A, Colored by Iterations for A^-¹ ');

% Create colorbar
colorbar('peer',axes1);

